from random import choice
import namesastral, namesalien, namesanimal, unicodedata

def generate_name_grams(nameList):
    """
    Generates the lists of the various n-grams that are used to generate
    names. Returns the lists in a tuple.

    Parameters:
        nameList: List of strings
            A list of names to break up into n-grams.
    """
    nameListClean = [ unicodedata.normalize("NFKC", name) for name in nameList ]
    firstGrams = list(set([ name[0] for name in nameListClean ]))
    firstBiGrams = list(set([ name[:2] for name in nameListClean ]))
    firstTriGrams = list(set([ name[:3] for name in nameListClean ]))
    firstFourGrams = list(set([ name[:4] for name in nameListClean ]))
    fourGramsSet = set()
    for name in nameListClean:
        namePart = name[1:-2]
        for x in range(len(namePart)):
            if x + 4 > len(namePart):
                continue
            else:
                fourGramsSet.add(namePart[x:x + 4])
    fourGrams = list(fourGramsSet)
    lastFourGrams = list(set([ name[-4:] for name in nameListClean ]))
    nameLength = [ len(name) for name in nameListClean ]

    return (firstGrams, firstBiGrams, firstTriGrams, firstFourGrams, fourGrams, lastFourGrams, nameLength)

def generate_name(nGrams, existingNames):
    """
    Generates a name based on lists of n-grams passed in. It will also
    make sure a duplicate name is not created by referencing another
    list of names passed in.

    Parameters:
        nGrams: Tuple of lists of strings
            A tuple containing lists of n-grams to be used to generate names.
            Also contains a list of name lengths.
        existingNames: List of strings
            A list of names that have already been generated or you don't
            want to be generated by this function.
    """
    firstGrams = nGrams[0]
    firstBiGrams = nGrams[1]
    firstTriGrams = nGrams[2]
    firstFourGrams = nGrams[3]
    fourGrams = nGrams[4]
    lastFourGrams = nGrams[5]
    nameLengths = nGrams[6]
    
    while True:
        length = choice(nameLengths)
        name = choice(firstGrams)
        name += choice([ biGram[-1] for biGram in firstBiGrams if biGram[0] == name ])
        name += choice([ triGram[-1] for triGram in firstTriGrams if triGram[:2] == name ])
        name += choice([ fourGram[-1] for fourGram in firstFourGrams if fourGram[:3] == name ])

        while name != None and len(name) < length - 2:
            choices = [ fourGram[-1] for fourGram in fourGrams if fourGram[:3] == name[-3:] ]
            if len(choices) > 0:
                name += choice(choices)
            else:
                break
        choices = [ fourGram[-2:] for fourGram in lastFourGrams if fourGram[:2] == name[-2:] ]

        if len(choices) > 0:
            name += choice(choices)
        else:
            continue

        name = name.replace("_", " ")

        if len(name) == length and name not in existingNames and name != "Terra" and name != "Luna" and name != "Terran":
            break
        
    return name

def generate_animal_name(nGrams):
    """
    Generates a name based on lists of n-grams passed in. The differences
    between this function and the one above it is that this function is
    designed to create two names, like a scientific name for an organism.
    To help prevent duplicate names, if a short length is chosen for the
    first name, a longer name must be chosen for the second name. Because
    there are so many animals generated, this does not check for duplicate
    names. You'll just have to hope you don't run into one.

    Parameters:
        nGrams: Tuple of lists of strings
            A tuple containing lists of n-grams to be used to generate names.
            Also contains a list of name lengths.
    """
    firstGrams = nGrams[0]
    firstBiGrams = nGrams[1]
    firstTriGrams = nGrams[2]
    firstFourGrams = nGrams[3]
    fourGrams = nGrams[4]
    lastFourGrams = nGrams[5]
    nameLengths = nGrams[6]
    
    while True:
        length1 = choice(nameLengths)
        name1 = choice(firstGrams)
        name1 += choice([ biGram[-1] for biGram in firstBiGrams if biGram[0] == name1 ])
        name1 += choice([ triGram[-1] for triGram in firstTriGrams if triGram[:2] == name1 ])
        name1 += choice([ fourGram[-1] for fourGram in firstFourGrams if fourGram[:3] == name1 ])

        while name1 != None and len(name1) < length1 - 2:
            choices = [ fourGram[-1] for fourGram in fourGrams if fourGram[:3] == name1[-3:] ]
            if len(choices) > 0:
                name1 += choice(choices)
            else:
                break
        choices = [ fourGram[-2:] for fourGram in lastFourGrams if fourGram[:2] == name1[-2:] ]

        if len(choices) > 0:
            name1 += choice(choices)
        else:
            continue

        if len(name1) == length1:
            break
        
    while True:
        #This ensures that if a shorter first name was chosen, a longer second name is chosen
        #If a longer first name is chosen, the minimum length of the second name is still 4.
        secondNameLengths = list(range(max([ 4, max(nameLengths) - length1 ]), max(nameLengths) + 1))
        length2 = choice(secondNameLengths)
        name2 = choice(firstGrams)
        name2 += choice([ biGram[-1] for biGram in firstBiGrams if biGram[0] == name2 ])
        name2 += choice([ triGram[-1] for triGram in firstTriGrams if triGram[:2] == name2 ])
        name2 += choice([ fourGram[-1] for fourGram in firstFourGrams if fourGram[:3] == name2 ])

        while name2 != None and len(name2) < length2 - 2:
            choices = [ fourGram[-1] for fourGram in fourGrams if fourGram[:3] == name2[-3:] ]
            if len(choices) > 0:
                name2 += choice(choices)
            else:
                break
        choices = [ fourGram[-2:] for fourGram in lastFourGrams if fourGram[:2] == name2[-2:] ]

        if len(choices) > 0:
            name2 += choice(choices)
        else:
            continue

        if len(name2) == length2:
            break
        
    name = name1 + " " + name2

    return name

astralNGrams = generate_name_grams(namesastral.names)
alienNGrams = generate_name_grams(namesalien.names)
animalNGrams = generate_name_grams(namesanimal.names)
